from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SERVICES = ROOT / "services"
API_ROOT = ROOT / "apps" / "api"
if str(SERVICES) not in sys.path:
    sys.path.insert(0, str(SERVICES))
if str(API_ROOT) not in sys.path:
    sys.path.insert(0, str(API_ROOT))

from hearthview.models import ProjectModel  # noqa: E402
from hearthview_api.api_models import (  # noqa: E402
    BlenderCapabilityResponse,
    A1TraceResponse,
    CompileRequest,
    GeometryResponse,
    ProjectCreate,
    ProjectResponse,
    RenderJobRequest,
    RenderJobResponse,
    ReviewEventRequest,
    ReviewItemResponse,
    RevisionResponse,
    SourceResponse,
    ValidationRunResponse,
)


SCHEMA_PATH = ROOT / "packages" / "contracts" / "schema.json"
TYPES_PATH = ROOT / "apps" / "web" / "src" / "api" / "types.ts"


def render_schema() -> str:
    schema = ProjectModel.model_json_schema(mode="serialization")
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def _type_for(schema: dict[str, Any], property_name: str | None = None) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_type_for(choice, property_name) for choice in schema["anyOf"])
    if schema.get("type") == "array":
        if "prefixItems" in schema:
            return "readonly [" + ", ".join(_type_for(item) for item in schema["prefixItems"]) + "]"
        return f"ReadonlyArray<{_type_for(schema.get('items', {}))}>"
    if schema.get("type") == "string":
        return "TickString" if property_name and property_name.endswith("_ticks") else "string"
    if schema.get("type") in {"integer", "number"}:
        return "number"
    if schema.get("type") == "boolean":
        return "boolean"
    if schema.get("type") == "null":
        return "null"
    if schema.get("type") == "object":
        return "Record<string, unknown>"
    return "unknown"


def _interface(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in schema.get("properties", {}).items():
        optional = "" if property_name in required else "?"
        lines.append(
            f"  readonly {property_name}{optional}: {_type_for(property_schema, property_name)};"
        )
    lines.append("}")
    return "\n".join(lines)


def render_typescript() -> str:
    domain_schema = ProjectModel.model_json_schema(mode="serialization")
    boundary_models = (
        ProjectCreate,
        A1TraceResponse,
        ProjectResponse,
        SourceResponse,
        ReviewItemResponse,
        ReviewEventRequest,
        RevisionResponse,
        ValidationRunResponse,
        CompileRequest,
        GeometryResponse,
        BlenderCapabilityResponse,
        RenderJobRequest,
        RenderJobResponse,
    )
    sections = [
        "// Generated by scripts/generate_contracts.py. Do not edit by hand.",
        "",
        "export type TickString = string & { readonly __tickBrand: unique symbol };",
    ]
    emitted: set[str] = set()

    def append_definition(name: str, definition: dict[str, Any]) -> None:
        if name in emitted:
            return
        emitted.add(name)
        sections.append("")
        if definition.get("type") == "object":
            sections.append(_interface(name, definition))
        else:
            sections.append(f"export type {name} = {_type_for(definition)};")

    for name, definition in domain_schema.get("$defs", {}).items():
        append_definition(name, definition)
    append_definition(domain_schema["title"], domain_schema)
    for model in boundary_models:
        schema = model.model_json_schema(mode="serialization")
        for name, definition in schema.get("$defs", {}).items():
            append_definition(name, definition)
        append_definition(schema["title"], schema)
    sections.append("")
    return "\n".join(sections)


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate HearthView boundary contracts.")
    parser.add_argument("--check", action="store_true", help="Fail when generated files are stale.")
    args = parser.parse_args()
    results = (
        _write_or_check(SCHEMA_PATH, render_schema(), args.check),
        _write_or_check(TYPES_PATH, render_typescript(), args.check),
    )
    if not all(results):
        print("Generated contracts are stale. Run scripts/generate_contracts.py.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
