// Generated by scripts/generate_contracts.py. Do not edit by hand.

export type TickString = string & { readonly __tickBrand: unique symbol };

export interface FixedObject {
  readonly id: string;
  readonly kind: "TV";
  readonly host_wall_id: string;
  readonly start_ticks: TickString;
  readonly end_ticks: TickString;
  readonly source_ref_ids: ReadonlyArray<string>;
}

export interface Island {
  readonly id: string;
  readonly width_ticks: TickString;
  readonly depth_ticks: TickString;
  readonly x_ticks: TickString;
  readonly y_ticks: TickString;
  readonly source_ref_ids: ReadonlyArray<string>;
}

export interface ReviewDecision {
  readonly item_id: string;
  readonly state?: ReviewState;
}

export type ReviewState = "UNREVIEWED" | "APPROVED" | "EDITED_APPROVED" | "REJECTED" | "CONFLICT";

export interface SourceDocument {
  readonly id: string;
  readonly display_name: string;
  readonly sha256: string;
  readonly page_count: number;
  readonly profile: "GARRIGAN_A1" | "UNSUPPORTED";
}

export interface SourceReference {
  readonly id: string;
  readonly source_id: string;
  readonly page_number: number;
  readonly pdf_polygon: ReadonlyArray<readonly [number, number]>;
  readonly rationale: string;
}

export interface Wall {
  readonly id: string;
  readonly name: string;
  readonly axis: "X" | "Y";
  readonly origin_x_ticks: TickString;
  readonly origin_y_ticks: TickString;
  readonly length_ticks: TickString;
  readonly thickness_ticks: TickString;
  readonly height_ticks: TickString;
  readonly ordered_children: ReadonlyArray<WallChild>;
  readonly source_ref_ids: ReadonlyArray<string>;
}

export interface WallChild {
  readonly id: string;
  readonly kind: "WINDOW" | "SOLID_MOUNT_ZONE" | "UNFRAMED_OPENING" | "SOLID";
  readonly start_ticks: TickString;
  readonly end_ticks: TickString;
  readonly connects_to?: string | null;
  readonly source_ref_ids: ReadonlyArray<string>;
}

export interface ProjectModel {
  readonly id: string;
  readonly name: string;
  readonly schema_version?: string;
  readonly revision?: number;
  readonly level_height_ticks?: TickString;
  readonly source_documents?: ReadonlyArray<SourceDocument>;
  readonly source_references?: ReadonlyArray<SourceReference>;
  readonly walls?: ReadonlyArray<Wall>;
  readonly fixed_objects?: ReadonlyArray<FixedObject>;
  readonly island?: Island | null;
  readonly review_decisions?: ReadonlyArray<ReviewDecision>;
}

export interface ProjectCreate {
  readonly name: string;
}

export interface PdfRectResponse {
  readonly x0: number;
  readonly y0: number;
  readonly x1: number;
  readonly y1: number;
}

export interface TraceGeometryResponse {
  readonly points: ReadonlyArray<readonly [number, number]>;
  readonly closed: boolean;
}

export interface TraceRecordResponse {
  readonly id: string;
  readonly kind: string;
  readonly room: string;
  readonly provenance: string;
  readonly geometry: TraceGeometryResponse;
  readonly source_page: number;
  readonly dimension_labels: ReadonlyArray<string>;
}

export interface TraceSummaryResponse {
  readonly verified: number;
  readonly traced: number;
  readonly ambiguous: number;
}

export interface A1TraceResponse {
  readonly page_number: number;
  readonly page_width_points: number;
  readonly page_height_points: number;
  readonly proposed_crop: PdfRectResponse;
  readonly records: ReadonlyArray<TraceRecordResponse>;
  readonly summary: TraceSummaryResponse;
  readonly approval_blocked: boolean;
}

export interface ProjectResponse {
  readonly id: string;
  readonly name: string;
  readonly revision: number;
}

export interface SourceResponse {
  readonly id: string;
  readonly display_name: string;
  readonly sha256: string;
  readonly byte_count: number;
  readonly page_count: number;
}

export interface ReviewItemResponse {
  readonly id: string;
  readonly title: string;
  readonly question: string;
  readonly help_text: string;
  readonly source_ref_id: string;
  readonly field_name: string | null;
  readonly value: string | null;
  readonly state: ReviewState;
}

export interface ReviewEventRequest {
  readonly id: string;
  readonly base_revision: number;
  readonly operation: string;
  readonly item_id: string;
  readonly payload?: Record<string, unknown>;
  readonly source_ref_ids?: ReadonlyArray<string>;
  readonly rationale: string;
}

export interface RevisionResponse {
  readonly revision: number;
}

export interface ValidationIssue {
  readonly code: string;
  readonly severity: "BLOCKING" | "WARNING";
  readonly message: string;
  readonly action: string;
  readonly element_id?: string | null;
  readonly review_item_id?: string | null;
}

export interface ValidationReport {
  readonly status: "READY_TO_VIEW" | "NEEDS_INPUT" | "CONFLICTING_INFORMATION";
  readonly model_hash: string;
  readonly schema_hash: string;
  readonly validator_version: string;
  readonly blocking_count: number;
  readonly evidence_coverage_percent: number;
  readonly issues: ReadonlyArray<ValidationIssue>;
}

export interface ValidationToken {
  readonly token_hash: string;
  readonly model_hash: string;
  readonly report_hash: string;
  readonly schema_hash: string;
  readonly validator_version: string;
}

export interface ValidationRunResponse {
  readonly report: ValidationReport;
  readonly token: ValidationToken | null;
}

export interface CompileRequest {
  readonly token: ValidationToken;
}

export interface GeometryResponse {
  readonly artifact_id: string;
  readonly model_hash: string;
  readonly geometry_hash: string;
  readonly glb_file_hash: string;
  readonly island_dimensions: string;
  readonly primitive_count: number;
  readonly bounds_ticks: readonly [string, string, string, string, string, string];
  readonly download_url: string;
}

export interface BlenderCapabilityResponse {
  readonly available: boolean;
  readonly executable: string | null;
  readonly version: string | null;
  readonly message: string;
  readonly action: string | null;
}

export interface RenderJobRequest {
  readonly geometry_artifact_id: string;
  readonly camera: string;
  readonly quality: string;
  readonly width: number;
  readonly height: number;
  readonly style: string;
}

export interface RenderJobResponse {
  readonly id: string;
  readonly status: string;
  readonly geometry_hash: string;
  readonly image_url: string | null;
  readonly message: string;
}
